// Code generated by goctl. DO NOT EDIT.
package types

type Asset struct {
	ReadResponse
}

type History struct {
	EndedAt    string   `json:"ended_at"`
	StartedAt  string   `json:"started_at"`
	Timestamps []string `json:"timestamps"`
}

type Medication struct {
	BrandName   string `json:"brand_name"`
	EndAfterN   int    `json:"end_after_n"`
	Frequency   string `json:"frequency"`
	GenericName string `json:"generic_name"`
}

type DispatchRequest struct {
	DispatchDate string       `json:"dispatch_date"`
	Medications  []Medication `json:"medications"`
}

type DispatchResponse struct {
	DispatchId string `json:"dispatch_id"`
}

type QueryRequest struct {
	GenericName string   `path:"gn"`
	Timestamps  []string `path:"ts"`
}

type QueryResponse struct {
	ComplianceRate float64 `json:"compliance_rate"`
}

type ReadRequest struct {
	Id    string `path:"id,optional"`
	Limit int    `path:"lim,optional"`
}

type ReadResponse struct {
	DispatchDate string       `json:"dispatch_date"`
	DispatchId   string       `json:"dispatch_id"`
	History      History      `json:"history"`
	Medications  []Medication `json:"medications"`
}

type UpdateRequest struct {
	DispatchId string 	`json:"id"`
	Timestamps []string `json:"timestamps"`
}

type UpdateResponse struct {
	Status string `json:"status"`
}