// Code generated by goctl. DO NOT EDIT.
package types

type History struct {
	EndedAt    string   `json:"ended_at"`
	StartedAt  string   `json:"started_at"`
	Timestamps []string `json:"timestamps"`
}

type Medication struct {
	BrandName   string `json:"brand_name"`
	EndAfterN   int    `json:"end_after_n"`
	Frequency   string `json:"frequency"`
	GenericName string `json:"generic_name"`
}

type DispatchRequest struct {
	Medications []Medication `form:"medications"`
}

type DispatchResponse struct {
	DispatchId string `json:"dispatch_id"`
}

type QueryRequest struct {
	GenericName string   `path:"gn"`
	Timestamps  []string `path:"ts"`
}

type QueryResponse struct {
	ComplianceRate float64 `json:"compliance_rate"`
}

type ReadRequest struct {
	Id string `path:"id"`
}

type ReadResponse struct {
	DispatchId  string       `json:"dispatch_id"`
	History     History      `json:"history"`
	Medications []Medication `json:"medications"`
}

type UpdateRequest struct {
	DispatchId string `path:"id"`
}
