// Code generated by goctl. DO NOT EDIT.
package types

type History struct {
	EndedAt    string   `json:"ended_at"`
	StartedAt  string   `json:"started_at"`
	Timestamps []string `json:"timestamps"`
}

type Medication struct {
	BrandName   string `json:"brand_name"`
	EndAfterN   int    `json:"end_after_n"`
	Frequency   string `json:"frequency"`
	GenericName string `json:"generic_name"`
}

type Request struct {
	Id string `path:"id"`
}

type Response struct {
	DispatchId  string       `json:"dispatch_id"`
	History     History      `json:"history"`
	Medications []Medication `json:"medications"`
}
